name: Trigger build cross multiple repositories

on:
  issue_comment:
    types: [created]

jobs:
  call_workflow:
    uses: wangchen7722/blueos-kernel/.github/workflows/reusable_cross_repos_build.yml@main
